services:
  neko-site:
    image: registry.yami.town/neko-site/neko-site:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "127.0.0.1:3001:3000"
    restart: always
    network_mode: bridge
